# Generated by Django 3.2.4 on 2021-11-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womeninstem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namess', models.CharField(max_length=100)),
                ('story', models.CharField(max_length=500)),
                ('achievess', models.CharField(max_length=500)),
                ('vlink', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=500)),
            ],
        ),
    ]
